jQuery(document).ready(function($){var height_diff=$(window).height()- $('body').height();if(height_diff>0){$('#page-footer').css('margin-top',height_diff);}
$('.parallax-wheniwasbad').each(function(){var $bgobj=$(this);$(window).scroll(function(){var speed=($bgobj.data('bg-speed')>0?$bgobj.data('bg-speed'):1);var yPos=-($(window).scrollTop()/ speed);
var coords='50% '+ yPos+'px';$bgobj.css({backgroundPosition:coords});});});$('article.post').hover(function(){$('a.edit-post').show();},function(){$('a.edit-post').hide();});$('body').scrollspy({target:'#main-nav',offset:$('.navbar').height()+ 50});$('a[href*=#]:not([href=#])').click(function(){if(location.pathname.replace(/^\//,'')==this.pathname.replace(/^\//,'')&&location.hostname==this.hostname){var target=$(this.hash);target=target.length?target:$('[name='+ this.hash.slice(1)+']');if(target.length){var thetop;if($('body').hasClass('navbar-no-offset')){thetop=target.offset().top+ 1;}else if($('body').hasClass('navbar-fixed-offset')){thetop=target.offset().top- $('.navbar').height()+ 1;}
$('html,body').animate({scrollTop:thetop},1000);return false;}}});$('#menu_search_btn').focus(function(){$('#s').animate({width:'200px',padding:'7px 13px'},300);$(this).removeClass('search_hidden');$('#s').removeClass('search_hidden');$('#s').focus();});$('#s').blur(function(){$('#s').animate({width:'0',border:'none',padding:'0'},300);$('#menu_search_btn').addClass('search_hidden');$(this).addClass('search_hidden');});$(window).resize(function(){if($(document).width()<768){$('body').addClass('navbar-no-offset');$('header.navbar').addClass('navbar-static-top');$('header.navbar').removeClass('navbar-fixed-bottom');$('header.navbar').removeClass('navbar-fixed-top');$('body').removeClass('navbar-fixed-offset');$('#main_header.navbar-static-top').css('top',0);}else{$('#main_header.navbar-fixed-top').css('top',$('#wpadminbar').outerHeight());$('.navbar-brand').css('font-size','');if($('body').data('navpos')=='fixed'){if($('body').hasClass('navbar-no-offset')){$('body').removeClass('navbar-no-offset');$('body').addClass('navbar-fixed-offset');$('header.navbar').removeClass('navbar-static-top');$('header.navbar').addClass('navbar-fixed-top');}}}}).resize();$('.waypoint-title').each(function(){if($(document).width()>=768&&$('#main_header').hasClass('navbar-fixed-top')){var $this=$(this);$this.waypoint(function(direction){$('#main_header .subhead.navbar-brand').remove();var title;if(direction==='down'){title=$this.html();}else{var prev=$this.waypoint('prev');if(prev.length>0){title=$this.waypoint('prev').html();}else{return 0;}}
var elm='<span class="subhead navbar-brand"><i class="fa fa-angle-right" style="padding-right: 15px;"></i>';elm+=title;elm+='</span>';$('#logo').after(elm);$('#main_header .subhead.navbar-brand').fadeIn("fast");},{offset:$('#main_header').position().top+ $('#main_header').height()});}});});(function(w){if(!(/iPhone|iPad|iPod/.test(navigator.platform)&&navigator.userAgent.indexOf("AppleWebKit")>-1)){return;}
var doc=w.document;if(!doc.querySelector){return;}
var meta=doc.querySelector("meta[name=viewport]"),initialContent=meta&&meta.getAttribute("content"),disabledZoom=initialContent+",maximum-scale=1",enabledZoom=initialContent+",maximum-scale=10",enabled=true,x,y,z,aig;if(!meta){return;}
function restoreZoom(){meta.setAttribute("content",enabledZoom);enabled=true;}
function disableZoom(){meta.setAttribute("content",disabledZoom);enabled=false;}
function checkTilt(e){aig=e.accelerationIncludingGravity;x=Math.abs(aig.x);y=Math.abs(aig.y);z=Math.abs(aig.z);if(!w.orientation&&(x>7||((z>6&&y<8||z<8&&y>6)&&x>5))){if(enabled){disableZoom();}}
else if(!enabled){restoreZoom();}}
w.addEventListener("orientationchange",restoreZoom,false);w.addEventListener("devicemotion",checkTilt,false);})(this);